version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package spring-boot:repackage
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/appforfun-2.1.6.RELEASE.jar